import ImportMapClass from '../import/import_map.js';
import GenerateMapClass from '../generate/map/generate_map.js';

export default class ProjectMapClass
{
    constructor(core)
    {
        this.core=core;
    }
    
        //
        // initialize and release
        //
        
    initialize()
    {
    }
    
    release()
    {
    }
    
        //
        // general info
        //
        
    getSetup()
    {
        return(this.core.setup);
    }
    
    getCamera()
    {
        return(this.core.camera);
    }
    
        //
        // main map loader
        //
    
    async loadMap()
    {
        let importSettings=this.getImportSettings();
        let importMap,generateMap;
        
            // regular glTF map
            
        if (importSettings.autoGenerate===undefined) {
            importMap=new ImportMapClass(this.core);
            return(await importMap.load(importSettings));
        }
        
            // autogenerated map
            
        generateMap=new GenerateMapClass(this.core);
        return(generateMap.build(importSettings));
    }
    
    /**
     * Adds an entity to this map, should only be called when
     * the system calls the ready() method.
     * 
     * @entityClass {Class} Class of entity to spawn
     * @name {string} Name of entity
     * @position {PointClass} Position of entity
     * @angle {PointClass} Angle of entity
     * @data {Object} Additional user data for entity
     * @show {boolean} TRUE if entity is not hidden
     */
    addEntity(entityClass,name,position,angle,data,show)
    {
        let entity;
        
        entity=new entityClass(this.core,name,position,angle,data);
        entity.show=show;
        
        this.core.map.entityList.add(entity);
        
        return(entity);
    }
    
    /*
     * Override this to pass in the map JSON import
     * settings.
     * 
     * @returns {Object} Map setup object
     */
    getImportSettings()
    {
        return(null);
    }
    
    /**
     * Override this to finish anything that needs to be setup
     * in the map after it has been completely loaded.
     */
    ready()
    {
    }
}
